version: '3.1'
services:
  service_db:
    image: mysql:8.4.0
    container_name: container_my_jingxi
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test@db
      MYSQL_DATABASE: my_jingxi
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
